services:
  pinterest-backend:
    build: ./backend
    env_file: .envs/.local/.django
    restart: always
    # volumes:
    #   - ./backend:/backend

  pinterest-frontend:
    build: ./frontend
    env_file: .envs/.local/.next
    restart: always
    # volumes:
    #   - ./frontend:/frontend
    # command: npm run dev

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 2019:2019

  redis:
    image: redis:alpine
    expose:
      - 6379
