# Generated by Django 3.0.11 on 2020-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_cover',
            field=models.FileField(blank=True, upload_to='pinterest_clone/storage/board_covers/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
