# Generated by Django 3.0.11 on 2020-11-19 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201118_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_cover',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, to='core.Pin'),
        ),
    ]
